### ISSUE TITLE
ufo2ft generates invalid output when glyph name starts in #

### ISSUE THREAD

**Issue by brawer** [googlefonts/ufo2ft#175]
When a font contains glyphs whose names start with a `#`, e.g. `#Qtail`, ufo2ft should escape the `#` in its output. Currently, ufo2ft copies the string into its output without escaping, which leads to syntactically malformed feature files like this:

```
markClass _Qtail <anchor 183 79> @MC_#Qtail;
```

In feature file syntax, the `#` character starts a comment, so feaLib (and also any other feature files compiler) will choke on the output. See https://github.com/fonttools/fonttools/issues/1100 and  https://github.com/googlei18n/fontmake/issues/347.

**Comment by anthrotype** [comment]
It’s not that simple, because in Glyphs.app the meaning of those leading non-letter characters in the anchor names is actually to not output any glyph positioning rules for those.
Yes, ufo2ft should avoid creating invalid features by stripping or escaping those invalid chars in anchor names, but that still doesn’t match Glyphsapp behaviour.

**Comment by adrientetar** [comment]
> in Glyphs.app

That should be handled in glyphslib, no?

**Comment by moyogo** [comment]
>> in Glyphs.app

> That should be handled in glyphslib, no?

If one want’s to roundtrip between UFOs and a Glyphs file, no.

**Comment by anthrotype** [comment]
> https://glyphsapp.com/blog/new-features-in-glyphs-2-3 -> "State of Component Alignment" says "If, however, you want to prevent Glyphs from generating the positioning code, you can now prefix the anchor name with a non-letter"

I would not be against adding support for such a feature in ufo2ft mark feature writer, if that could be useful for UFO-only projects as well.
Even the "_" underscore prefix convention for attaching anchors is unofficial yet widely used.
Of course, I'd like to know more about how exactly this works in Glyphs.app. Based on that blog post, any anchor whose name start with a non-letter (even a digit?) should not be included in the mark/mkmk feature code. Am I correct, @schriftgestalt?

Would you guys see any issues if ufo2ft mark feature writer did the same by default?

**Comment by khaledhosny** [comment]
I don’t mind such a behavior myself, but I also think documenting all the anchor naming conversions used by ufo2ft is well due (since we apparently are not going to get robust anchor type support in UFO anytime soon).

**Comment by adrientetar** [comment]
I don't personally mind this in practice, but I wish it was put in the specification since it's going to change compiler behavior for existing UFOs.

**Comment by anthrotype** [comment]
As I said the underscore thing is not in the UFO spec either

**Comment by adrientetar** [comment]
yea I think the same of it. I don't oppose going ahead with \# right now, but we ought to put it in the standard otherwise it's gonna be like C compilers where each does mostly the same thing but has differences or specific syntax meaning the same file produces different results.

**Comment by khaledhosny** [comment]
Fixed in #869
