### ISSUE TITLE
Add support for dlng and slng

### ISSUE THREAD

**Issue by bobh0303** [googlefonts/ufo2ft#256]
Now that UFO3 spec includes `public.openTypeMeta` in [lib.plist](http://unifiedfontobject.org/versions/ufo3/lib.plist/), could we get support for `dlng` and `slng` [metadata tags](https://docs.microsoft.com/en-us/typography/opentype/spec/meta#metadata-tags)?

**Comment by anthrotype** [comment]
That would nice. We need the ufo2ft.outlineCompiler to build a `meta` table when the UFO lib contains that `public.openTypeMeta` value. It's a relatively simple table to build. It only has a `data` attribute which is a dictionary mapping four-letter tags to either bytes (for binary data) or unicode strings (for text).
Anyone would like to take this up and send a PR?

**Comment by anthrotype** [comment]
this is for reference:
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_m_e_t_a.py
https://github.com/fonttools/fonttools/blob/master/Tests/ttLib/tables/_m_e_t_a_test.py
