### ISSUE TITLE
MarkFeatureWriter does not allow multiple anchor marks on the same glyph

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/ufo2ft#303]
I believe this is a regression, since my font used to build fine with fontmake 1.4.0 (not sure what version of ufo2ft this used).

If a glyph has more than one mark anchor, e.g. `_mark1` and `_mark2` only one of them will end up in the generated mark classes. This is caused by the code in: https://github.com/googlei18n/ufo2ft/blob/39ab30c54ab71b24d96bb68e0965c41937d39b35/Lib/ufo2ft/featureWriters/markFeatureWriter.py#L361-L364

I don’t know what the rationale for this, but it is a severe limitation and breaks my fonts. OpenType allows any number of mark anchors on a glyphs and ufo2ft should allow this.

For testing, try building [Reem Kufi](https://github.com/alif-type/reem-kufi) with latest fontmake and ufo2ft, the string لأ should render like the first image below, but it now renders like the second:
![o](https://user-images.githubusercontent.com/93914/50339558-a5302900-0520-11e9-9861-a04081241f65.png) ![n](https://user-images.githubusercontent.com/93914/50339565-abbea080-0520-11e9-8a85-26c9af8b6338.png)

**Comment by anthrotype** [comment]
The chance was meant to match Glyphs.app behavior. The problem with multiple mark anchors on the same glyph is that the same glyph cannot belong to multiple mark classes within the same lookup subtable, and unlike before when we were creating one mark2base lookup for each markClass (thus they were always disjoint and the problem didn’t arise), we now make a single mark2base lookup.

**Comment by moyogo** [comment]
About that... Null anchors are read as anchors at (0, 0) by InDesign 14.0.1 and maybe others. We didn’t have this issue with split lookups.

**Comment by moyogo** [comment]
I don’t think we should match Glyphs.app here, or at least one should have the option not to.
If one diacritic has more than one mark anchor then the mark2base lookup should be split to preserve the anchors in the source files.

**Comment by anthrotype** [comment]
Sounds reasonable. I won’t be able to look into it before second week of March. But I’d happily review PR

**Comment by madig** [comment]
@schriftgestalt: Cosimo told me he did this to match what Glyphs is doing. How does Glyphs handle this case?

**Comment by schriftgestalt** [comment]
I don’t think Glyphs can handle multiple _mark anchors. Just to be sure, I can’t find the test font in the linked repo?

**Comment by khaledhosny** [comment]
> I don’t think Glyphs can handle multiple _mark anchors. Just to be sure, I can’t find the test font in the linked repo?

There is both UFO sources and generated OTFs in the repo.

**Comment by anthrotype** [comment]
I have a patch locally that uses `fontTools.misc.classifyTools.Classifier` to make disjoint sets of markClasses which I then use to build multiple lookup subtables to ensure that mark classes do not intersect. Unfortunately it isn't ready to push and am going on vacation tomorrow. I will continue work on this when I am back in mid July.

**Comment by moyogo** [comment]
@anthrotype What’s the status of your patch? We can work on it if you share the branch?

**Comment by anthrotype** [comment]
@moyogo sorry I can't seem to find it any more... Do you want to take this up?
