### ISSUE TITLE
Add support for building GDEF LigatureCarets from "caret_X" anchors

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/ufo2ft#329]
Apparently Glyphs.app builds these now, and @schriftgestalt said they are implemented on Apple platform.  

see discussion in https://github.com/unified-font-object/ufo-spec/issues/89

**Comment by anthrotype** [comment]
I had forgotten that we do support these in fontmake, though only when building from glyphs sources:

https://github.com/googlefonts/glyphsLib/blob/9c12dc70c8d13f08d92b824e6710f6e3bb5037bb/Lib/glyphsLib/builder/features.py#L183

Still, would be nice to have a feature writer that would output these in features.fea from UFO sources

**Comment by benkiel** [comment]
This is now in the UFO spec: https://github.com/unified-font-object/ufo-spec/pull/90

**Comment by madig** [comment]
If this gets implemented, it would be nice if it could be appended to GDEF tables defined in `features.fea`. A project I'm working on defines an explicit GDEF GlyphClassDef but I'd love to leave out explicit LigatureCaretByPos statements because those are master/instance specific.

**Comment by moyogo** [comment]
Fixed in #480.
