### ISSUE TITLE
Compiling TrueType hints

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/ufo2ft#334]
I am thinking about the best way to support TrueType hint compilation in ufo2ft.

Say we have an external black box module that will take some information from the UFO and return hinting bytecode and related table values.

Where would I hook this into ufo2ft? I think either the `OutlineTTFCompiler` class, which looks complicated, because various tables would have to be modified based on if hinting is present or not; or to add it as a postProcessor which could modify the affected tables in one go. In OutlineTTFCompiler it would perhaps be easier to find the correct points to be hinted, because any point names/ids are still present, while in postProcessor I would have to map the hints to points by some heuristic.

Supporting this the way I plan would add two new optional dependencies to ufo2ft, the hint interpreter and a hinting language to bytecode compiler, probably [htic](https://gitlab.com/sev/htic).

Any opinions?

**Comment by jenskutilek** [comment]
After looking at `htic` again, I think a postprocessor is the way to go. There it is just one htic command to apply all the hinting code to all tables.

Not working yet, but it would look something like this: #335.

**Comment by madig** [comment]
I'm not too familiar with ufo2ft's internals, but if you're looking at the post-processing way, you could also just run `htic.toFontTools(hti_code, font)` after the `ufo2ft.compile*` call outside ufo2ft, no? In what context are you using `ufo2ft.compile*`?

**Comment by jenskutilek** [comment]
I'm using ufo2ft via fontmake, so I hoped to include the TT code compilation in ufo2ft.

**Comment by anthrotype** [comment]
hi jens. It's the first time I hear about this htic, I'll have a look at some point.
Ideally, I'd like the ufo2ft PostProcessor to be modular and pluggable like the PreProcessor, so that one can load custom post-processing filters as dynamic plugins. However at the moment i'm busy with other things and don't have much time to work on this.
I would recommend that for now you simply make a console script for this htic compiler and call that after you run fontmake.

**Comment by jenskutilek** [comment]
htic is quite handy, but uses its own mid-level hinting language (between high-level and pure assembly). I hope I can show you more in the near future, it looks very promising.

**Comment by jenskutilek** [comment]
The code in the [pull request](https://github.com/googlefonts/ufo2ft/pull/335) is working now if you have my fork of [htic](https://gitlab.com/jenskutilek/htic) installed. I posted a demo UFO with htic code at the current [UFO spec TT discussion](https://github.com/unified-font-object/ufo-spec/issues/93#issuecomment-496884658). You can build it with fontmake:

```bash
$ fontmake -u "IBM Plex Serif-Text.ufo" -o ttf --keep-overlaps --keep-direction --output-path "IBM Plex Serif-Text.ttf"
```

I would like to wait what comes from the UFO spec discussion, and then either use the htic compiler, or, if the format of choice should be the FontTools assembly representation, change my code so only existing FontTools assembly will compiled into the TTF. The step to build TT assembly from htic could would then be outside the scope of ufo2ft, I think.
