### ISSUE TITLE
vfb2ufo and OpenType classes

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/ufo2ft#349]
I noticed when trying to build fonts from UFOs generated by `vfb2ufo`, that any groups defined in the FontLab groups panel end up in the UFO in `groups.plist` (as expected). But those are not available when compiling the OT features with `ufo2ft`.

I wonder if it is in the scope of `ufo2ft` to add any groups from groups.plist to the feature file before compiling the OT features? Or should it be done in a separate preprocessing step?

**Comment by anthrotype** [comment]
I think this is a FontLab-specific behavior. The UFO spec never explicitly said that groups.plist should be translated into equivalent glyph classes in features.fea. The meaning of groups.plist beyond kerning is unspecified.
The kerning groups are a different matter, in that you can't generate the kern feature without write them.
I think ufo2ft followed ufo2fdk in this, it doesn't do anything with the non-kerning groups.

**Comment by anthrotype** [comment]
I am not saying that we should not support this, just that that's not how groups.plist have been undestood in general.
@jenskutilek do you know RoboFont also adds glyph groups from groups.plist as opentype classes in features.fea, like FontLab does?

**Comment by jenskutilek** [comment]
No, RoboFont does not add groups to the feature code. They need to be defined in the features file.

**Comment by anthrotype** [comment]
> No, RoboFont does not add groups to the feature code. They need to be defined in the features file.

Yeah.. That's where ufo2ft is coming from.
I'm not sure what to do. Does FontLab VI still work the same in this regard?

**Comment by jenskutilek** [comment]
Yes, FontLab VI still adds the class definitions from its classes panel when compiling the OT features.

I think I'll write some preprocessing script to add the classes in my case.

But maybe it is a conceptual question. What are the non-kerning groups in `groups.plist` for if it doesn't end up in the font? Just font editor internal usage?

**Comment by anthrotype** [comment]
> What are the non-kerning groups in groups.plist for if it doesn't end up in the font? Just font editor internal usage?

spec says they are "arbitrary" so they an be used for anything really.

**Comment by anthrotype** [comment]
maybe you can open an issue in the UFO spec
