### ISSUE TITLE
Support writing the final autogenerated feature file somewhere

### ISSUE THREAD

**Issue by madig** [googlefonts/ufo2ft#353]
Useful for debugging. Maybe a new parameter on all `compile*` functions that is a IOBuffer that the feature file is written to. Then fontmake can be wired up to pass something in.

**Comment by typoman** [comment]
I was wondering how the feature generator could be used as a separate package. The mark and kern feature generators are very useful. Also the way ufo2ft uses subsetting to infer pseudo unicodes could be used elsewhere in designing fonts.

**Comment by madig** [comment]
You can call into ufo2ft directly. See e.g. the tests for what to do.

**Comment by anthrotype** [comment]
@typoman you can do like this

```
from ufo2ft.featureCompiler import parseLayoutFeatures
from ufo2ft.featureWriters import KernFeatureWriter, MarkFeatureWriter
from ufoLib2 import Font

# if you want to append to an existing features.fea, you must parse it first
font = Font.open("MyFont.ufo")
featureFile = parseLayoutFeatures(font)

# alternatively you can pass a new empty FeatureFile object
# from fontTools.feaLib.ast import FeatureFile
# featureFile = FeatureFile()

kernWriter = KernFeatureWriter(font, featureFile)

feaText = featureFile.asFea()

print(feaText)
```

**Comment by typoman** [comment]
Thank you very much!

**Comment by anthrotype** [comment]
@typoman I updated the code, the first iteration was incorrect
