### ISSUE TITLE
class of sub elements are lost

### ISSUE THREAD

**Issue by typemytype** [googlefonts/ufo2ft#363]
defcon has a handy to provide classes for sub elements, [see fe the init of a Font class ](https://github.com/robotools/defcon/blob/master/Lib/defcon/objects/font.py#L71-L73)

ufo2ft makes a copy but uses a glyph class without any reference of sub element classes. This is wrong. As parent object could depend on custom method.

https://github.com/googlefonts/ufo2ft/blob/master/Lib/ufo2ft/util.py#L99

I would advice to use a simple `defcon.Glyph` while copying instead of the `g.__class__` or use all the sub elements while init the glyph object like:

```python
g.__class__

def newGlyph(name):
    g = cls(
        contourClass=g.contourClass, 
        pointClass =g. pointClass, 
        componentClass = g.componentClass,
        anchorClass = g.anchorClass,
        guidelineClass = g.guidelineClass,
        libClass = g.libClass,
        imageClass = g.imageClass
    )
    g.name = name
    return g
```

**Comment by typemytype** [comment]
second thought: I guess there is no reason to keep the original class, a copy must maybe just be a simple `defcon.Glyph` object

```python
def newGlyph(name)
    g = defcon.Glyph()
    g.name = name
    return g
```

and third thought: Its maybe not a good plan to make the api between the ufoLib2 and defcon so different. According the spec a glyph name is not required, so on init of a glyph object the name should not be a requirement. But ufoLib2 makes it a required argument, I think this is wrong... and makes packages like ufo2ft complex where it should not be...

**Comment by anthrotype** [comment]
> defcon has a handy to provide classes for sub elements, see fe the init of a Font class

hm, I would think that such sub-elements custom classes should rather be attributes of a class, instead of a particular instance.

Could you maybe add a method to the defcon Glyph object that returns a callable that already embeds all the custom sub-element classes (using functools.partial to store them in the callable).

That way we can simply get that (instead of getting `glyph.__class__`) and initialize that for the new glyph.

> According the spec a glyph name is not required, so on init of a glyph object the name should not be a requirement

How can a glyph without a name feels odd to me. If anything it must have a name as soon as it is inserted into a layer (as they name is its key). I'll think about that a bit.

**Comment by anthrotype** [comment]
I mean something like this

```python
def getCustomClass(self):
    return functools.partial(self.__class__, contourClass=g.contourClass, pointClass=g.pointClass, ...)
```

I guess actually we can do that ourselves without needing a change on defcon side.

**Comment by anthrotype** [comment]
> Its maybe not a good plan to make the api between the ufoLib2 and defcon so different.

yeah, I'm also interested in improving that (see https://github.com/fonttools/ufoLib2/issues/41).

**Comment by anthrotype** [comment]
> I guess there is no reason to keep the original class, a copy must maybe just be a simple defcon.Glyph object

Sorry but how is `glyph.__class__` any different from `defcon.Glyph()`? Why would the latter fix the problem of referencing the sub-element classes while the former does not? I'm confused..

**Comment by typemytype** [comment]
defcon has `fontOrLayer.instantiateGlyphObject()` which returns a proper glyph object with all the correct reference set. 

a correction and improved patch:

```python
def newGlyph(name):
    g = g.layer.instantiateGlyphObject()
    g.name = name
    return g
```


> hm, I would think that such sub-elements custom classes should rather be attributes of a class, instead of a particular instance.

and when references are class attributes its not flexible enough... (not the issue here)

> Sorry but how is glyph.__class__ any different from defcon.Glyph()? 

its missing the sub element class references, where `glyph.__class__` requires the sub elements to be classes from the set sub element classes. This is how defcon is setup and how all sub elements are created.

**Comment by madig** [comment]
Hm. The code snippet won't easily work for ufoLib2, because its `Glyph` objects keep no reference to their parent layer. Renaming it should invoke `renameGlyph` instead of setting the `name` attr directly.

**Comment by anthrotype** [comment]
Let's at lease use that method in ufo2ft when using defcon backend
