### ISSUE TITLE
Experiencing very slow OTF builds in FontMake build: "INFO:ufo2ft.postProcessor:Subroutinizing CFF table"

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/ufo2ft#373]
I'm not sure whether this is tied to this issue or not: 

> Consider (optionally) using tx instead of compreffor #372

...but I'm running into extremely long builds for OTFs with FontMake.

Everything goes extremely fast, until it hits this:

```
INFO:ufo2ft.postProcessor:Subroutinizing CFF table
```

...and then my fans whir up and things grind to a halt. I left my computer for an hour or two, and only 3 instances out of 33 had built into static OTFs.

Are there any tactics that I might use to investigate this problem any further?

Thank you so much for any tips or insight!

**Comment by madig** [comment]
How many glyphs are in your instances? The issue you linked is related, as compreffor is very slow. Try subroutinizing with tx instead.

**Comment by arrowtype** [comment]
Hey @madig, thanks for your reply! 

I have about 285 glyphs in this typeface, many of which are comprised of components (it's a basic Latin character set, currently).

Sorry if this is a basic question, but do you happen to know if there is a way to use tx directly in FontMake, or would I have to make a custom build tool?

I did find the fontmake option `--optimize-cff 0`, which prevents subroutinization. Probably not optimal in the long run, but it let things build nice and quickly, which was the most important thing for now. Should have looked at the `--help` doc before asking for tips!

**Comment by madig** [comment]
As discussed in https://github.com/googlefonts/ufo2ft/issues/372, integrating tx into fontmake somehow is desireable, but noone put in the work yet. You'll have to insert an additional step in your pipeline yourself.

**Comment by anthrotype** [comment]
@arrowtype I integrated cffsubr support in ufo2ft with #383. Now I have to update fontmake to optionally use that. What is the font you were building that would take so long, so I can run some tests?

**Comment by khaledhosny** [comment]
The cffsubr option has been the default for sometime.
