### ISSUE TITLE
Variable ttf without component decomposition

### ISSUE THREAD

**Issue by kontur** [googlefonts/ufo2ft#379]
I'm working on a variable pixel font that has all its 1000k+ glyphs constructed from a single component, which gets manipulated on three axes. [Looking at the code](https://github.com/googlefonts/ufo2ft/blob/b35c4a89bab6b6f9e25e6c9cf9d405067126fa9c/Lib/ufo2ft/preProcessor.py#L259) there does not seem to be an easy way to disable decomposing components aside from subclassing the preprocessor (maybe I am missing something obvious). In this particular case we have 30+ masters and the build decomposing all glyphs bloats the font to the point of not compiling at all, when simply modulating the component seems an elegant and efficient way to achieve this.

Is there some technical limitation due to which uft2ft opts to always decompose, or has there simply not been a case for being able to control this via a flag? 

This use case aside, in terms of efficiency I don't understand why the default would be to always decompose all components, or am I interpreting the code and my debug traces with sample fonts wrong?

**Comment by madig** [comment]
For TTFs, decomposing happens when you mix outlines and components because TTF can have either/or bot not both. For CFF, it always happens because there are no components in CFF and you have to use a subroutinizer to factor them out again.

**Comment by kontur** [comment]
Ah, yes, so I had tried via fontmake with the `-o variable` so that would be TTF, essentially using [this](https://github.com/googlefonts/ufo2ft/blob/66510c8128f9a447617c8c4d6d5871ef4577f74f/Lib/ufo2ft/__init__.py#L327) I suppose.

So my test file has 1000k glyphs with "twice nested" components, meaning each glyph has x `componentA` which contains one `componentB` — is it a bug that ufo2ft would decompose those?

**Comment by madig** [comment]
Non-decidable without some source to test this with.

**Comment by anthrotype** [comment]
We only decompose mixed contours+components glyphs which are impossible in TrueType. You need to make sure that if you want to keep a glyph as a composite glyph you only use components and not also contours.

**Comment by kontur** [comment]
Hm, okay, I'll dig deeper in the sources and report back. So the assumption is that it _should not_ decompose for a simple, untransformed, not-nested component using that TTF compile method.

**Comment by anthrotype** [comment]
we don't check transforms or nesting level, only whether a glyph contains both components and contours

https://github.com/googlefonts/ufo2ft/blob/66510c8128f9a447617c8c4d6d5871ef4577f74f/Lib/ufo2ft/preProcessor.py#L156-L158

**Comment by anthrotype** [comment]
in general decomposition is not an optional thing, but is required by the output font formats, if we weren't doing it here fonttools TT and Charstring pens would do it for us later anyway. We do it before we remove the overlaps (for statics) so that we can union contours + decomposed components as needed.

**Comment by kontur** [comment]
I haven't managed to fully narrow down as to why my initial test file did decompose the components but with a super-minimal subset it works as should and retains the components. The initial outcome has led me to some wrong assumptions, which you have clarified and I could since confirm wrong ;)
