### ISSUE TITLE
Ambiguous direction for Arabic script numbers

### ISSUE THREAD

**Issue by typoman** [googlefonts/ufo2ft#384]
Here is the error:
```
| WARNING :ufo2ft.featureWriters.kernFeatureWriter.KernFeatureWriter:skipped kern pair with ambiguous direction: <KerningPair arabicDateSeperator charArabic -13 {'RTL'} {'L', 'R'}>
```
Pair example:
`١؍` or `؍١`

Both should be LTR as both are LTR glyphs or is this an ambiguity from unicode?

**Comment by madig** [comment]
The latter I think.

**Comment by typoman** [comment]
Another issue is that Arabic date separator is not RTL and should be considered neutral or LTR. This is wrong from unicode:
https://www.compart.com/en/unicode/U+060D

Maybe these need to be hard coded in font tools. Should I open an issue?

**Comment by typoman** [comment]
@roozbehp

**Comment by anthrotype** [comment]
yes, it looks like ARABIC DATE SEPARATOR is classified as Bidi Category "AL" which would imply strong right-to-left direction. Ufo2ft is thus skipping the ambiguous kerning pair against arabic numerals (which are LTR).
I am not sure what the fix here should be. The whole support for kerning of arabic numbers is problematic across different implementations (see #198). I'm inclined to close as wontfix

**Comment by belluzj** [comment]
If it is indeed the case that the date separator should be neutral or LTR, is it possible to report this Unicode so they can fix it at the source?

**Comment by typoman** [comment]
Another proposal for a fix, how about a glyph lib key for direction? There are also glyphs without unicode. That could override any other data like unicode.

**Comment by typoman** [comment]
No idea about this getting fixed from unicode, I mentioned roozbeh. Maybe he will respond.

**Comment by anthrotype** [comment]
even if you fixed that in the font, I believe layout engines that uses unicode data to segment strings into substrings with uniform diectionality would still treat the two characters as belonging to distinct runs, so kern feature would not work across them. Am I right @khaledhosny ?

**Comment by anthrotype** [comment]
@typoman if you manage to produce a test font in which those particular kern pairs work in some implementation (e.g. harfbuzz, directwrite, coretext), then I am willing to review a patch that somehow works around this incorrect BiDi classification.

**Comment by khaledhosny** [comment]
From what I can tell, the date separator gets its own RTL bidi level, so it can’t e kerned against numbers:
```
$ echo "١؍٢" | fribidi --levels
2 1 2
```

**Comment by typoman** [comment]
I guess this can be closed since this is not an issue that can be solved by ufo2ft. I still would appreciate if anyone can direct me how can I bring this up with unicode. Thank you all for your precious time.

**Comment by typoman** [comment]
I filed the error report to the Unicode website!
