### ISSUE TITLE
MarkFeatureWriter should not write markClass statements for non-exporting glyphs

### ISSUE THREAD

**Issue by kontur** [googlefonts/ufo2ft#411]
It appears the MarkFeatureWriter does not consider the UFO's `public.skipExportGlyphs` list and generates `markClass` statements also for any non-exporting mark glyphs, which will subsequently be missing from the font and throw an error on compile.

Take a [UFO font](https://www.dropbox.com/sh/qe2jewtd50skqj5/AAD0Buuf9baQr_7qcvOfmE53a?dl=0) with only `A` and non-exporting `dieresiscomb` like this:

<img width="519" alt="Screenshot 2020-10-21 at 15 23 28" src="https://user-images.githubusercontent.com/1893577/96719218-ca5a8080-13b1-11eb-8c3c-b7e2a2376dcd.png">

And running this script:
```
from ufo2ft.featureWriters import MarkFeatureWriter
from fontTools.feaLib.ast import FeatureFile
from defcon import Font

font = Font("Testfont-Regular.ufo")
fea = FeatureFile()
markWriter = MarkFeatureWriter()
markWriter.write(font, fea)

print(fea.asFea())
```

Will output:
```
markClass u0308 <anchor 300 700> @MC_top;

feature mark {
    lookup mark2base {
        pos base u0041 <anchor 340 700> mark @MC_top;
    } mark2base;

} mark;

feature mkmk {
    lookup mark2mark_top {
        @MFS_mark2mark_top = [u0308];
        lookupflag UseMarkFilteringSet @MFS_mark2mark_top;
        pos mark u0308 <anchor 300 900> mark @MC_top;
    } mark2mark_top;

} mkmk;
```

ufo2ft's MarkFeatureWriter (and possibly KernFeatureWriter?) should ignore non-exporting mark glyphs. The above output is from version `2.16.0`.

**Comment by kontur** [comment]
I've added a second UFO to the link above to test the commit in the PR. For a font with only the non-exporting mark no markClass and mark code is generated, for the second UFO that has the non-exporting mark as well as an exporting `macroncomb` mark the markClass statements get generated only for the exporting mark and dropping the non-exporting one as expected.

**Comment by typoman** [comment]
ufo2ft is part of fontmake and if you compile the font using fontmake, those glyphs won't be included. You can subset the font before generating the mark feature using this code, but I recommend not generating the mark features as fontmake adds it to the binary, and it already exists in form of anchors in the UFO.
```py
class SubsetFont(dict):
	"""
	A dict that resembles a font with a glyph subset from
	public.skipExportGlyphs. This is just a fast way to subset
	a font and generate mark features for it.
	"""

	def __new__(cls, font, subset=None):
		skipExportGlyphs = font.lib.get("public.skipExportGlyphs", [])
		if skipExportGlyphs != []:
			subsetFont = super().__new__(cls)
			if subset is None:
				subset = set(font.keys()) - set(skipExportGlyphs)
			subsetFont._subset = subset
			return subsetFont
		return font

	def __init__(self, font):
		super().__init__()
		subset = self._subset
		for gname in subset:
			self[gname] = font[gname]
		self.path = font.path
		self.glyphOrder = [g for g in font.glyphOrder if g in subset]
		self.lib = dict(font.lib)
		self.lib["public.glyphOrder"] = self.glyphOrder
		self.groups = {}
		for groupName, groupMembers in font.groups.items():
			newMembers = [g for g in groupMembers if g in subset]
			if newMembers:
				self.groups[groupName] = newMembers
		self.info = font.info
```

**Comment by kontur** [comment]
Well, my issue is precisely that I want to explicitly generate the mark code, do some manipulation to it, and then later compile the font using my precompiled feature code. Since e.g. fontmake compiles this code normally when it runs there is no way to interact with it without pre-compiling it.

What would be the reasoning _not to_ prune the generated mark code in ufo2ft based on what information is in the UFO explicitly marking some glyphs as not included?

So the code you posted would be to get a `font` object to pass to the `write` method?

**Comment by typoman** [comment]
> So the code you posted would be to get a `font` object to pass to the `write` method?

Exactly, as in your example:
```py
font = SubsetFont(Font("Testfont-Regular.ufo"))
```

**Comment by anthrotype** [comment]
I agree, the mark writer should take into account public.skipExportGlyphs lib key. Would you like to send a PR? I don't have time to work on this at the moment.

**Comment by anthrotype** [comment]
Oh sorry! I see now you did send a PR already :)
I'll take a look soon

**Comment by kontur** [comment]
Cheers! Like I wrote in the PR I am not sure if my solution is in the right place, but at least for the test documents I linked above it works as intended.
