### ISSUE TITLE
Missing localized names from Glyphs

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/ufo2ft#420]
I'm working on putting together a font (UFO generated via glyphsLib) that has a Japanese localized name, but when building with `ufo2ft`, I am not seeing the localized name show up in the TTF name table. 

Here is the relevant key from the lib file:
    <key>com.schriftgestaltung.customParameter.GSFont.localizedFamilyName</key>
    <string>Japanese;つきみ丸ゴかな</string>

And a sample UFO that contains it:
[TsukimiRo-Light.ufo.zip](https://github.com/googlefonts/ufo2ft/files/5498973/TsukimiRo-Light.ufo.zip)

TBH, I'm not sure if this is an issue in ufo2ft, or fonttools itself, but thought I'd start here. Let me know if it should be moved over 😄

**Comment by madig** [comment]
I don't think we handle that key at all.

**Comment by aaronbell** [comment]
When you say that you don't handle that key at all, you mean that it doesn't get ported to the appropriate place in the UFO? So, if it is being properly handled by glyphsLib, ufo2ft / fonttools would implement it?

**Comment by madig** [comment]
> you mean that it doesn't get ported to the appropriate place in the UFO?

Yes.

> So, if it is being properly handled by glyphsLib, ufo2ft / fonttools would implement it?

Yes. You'd have to put it into the UFO's fontinfo NameRecords.

**Comment by aaronbell** [comment]
Alright. I'll open a bug over there!
