### ISSUE TITLE
flattenComponents breaks composed positioning on nested + transformed combining accent

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/ufo2ft#435]
I have attempted to use the `flattenComponents` filter in a UFO based on the advice here: https://github.com/googlefonts/fontbakery/issues/2961#issuecomment-733745539

```
<key>com.github.googlei18n.ufo2ft.filters</key>
    <array>
      <dict>
        <key>name</key>
        <string>flattenComponents</string>
        <key>pre</key>
        <integer>1</integer>
      </dict>
    </array>
```

It mostly works well! However, a notable exception is that my caroncomb accents, which are actually composed of the circumflexcomb rotated 180°. These caroncombs are decomposed, which is good, but the alignment in glyphs using them gets messed up once I use FontMake to export to a TTF:

![misaligned flattened components](https://user-images.githubusercontent.com/45946693/100262940-dbe7f880-2f1a-11eb-98f8-8853263419cd.png)

![image](https://user-images.githubusercontent.com/45946693/100263402-75afa580-2f1b-11eb-8fbb-f14379a211d2.png)

By comparison, here is a TTF built from a UFO that didn’t have a flattenComponents filter:

![good components alignment](https://user-images.githubusercontent.com/45946693/100262997-f02bf580-2f1a-11eb-866b-5fc24e5898d4.png)

These are not open-source UFOs, so I can try to report back later with an OS reproduction case, if that is needed to diagnose & fix this problem.

**Comment by anthrotype** [comment]
you may want to try using the decomposeTransformedComponents filter _before_ the flattenComponents

**Comment by arrowtype** [comment]
Thanks for the quick response! It works like a charm. 👍 

![image](https://user-images.githubusercontent.com/45946693/100264098-5e24ec80-2f1c-11eb-8598-269744b61891.png)

Cheers! Feel free to close this issue if you feel that this is handled as expected.

**Comment by anthrotype** [comment]
I would think so, yes. Cheers 🍻
