### ISSUE TITLE
Flattening components does not handle transformed components well

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/ufo2ft#442]
In [Test.glyphs](https://github.com/googlefonts/ufo2ft/files/5698865/Test.glyphs.zip) I have many rotated, translated, or flipped components, but flattening components seems to not handle all of them correctly.

In the [Test-Regular.ttf](https://github.com/googlefonts/ufo2ft/files/5698892/Test-Regular.ttf.zip) (built with `fontmake -f`), many components are mis positioned.

Below bad font (built with `-f` fontmake option) and above the good font (built without the option):
<img width="497" alt="image" src="https://user-images.githubusercontent.com/93914/102277540-1a2c7280-3f31-11eb-8bbd-e6c8b8a14822.png">

**Comment by khaledhosny** [comment]
(These are activated with `numr` feature).

**Comment by moyogo** [comment]
The issue is :
https://github.com/googlefonts/ufo2ft/blob/3ad75bf993f9ddb6c2f431c21e8293913e431054/Lib/ufo2ft/filters/flattenComponents.py#L47

Applying scale transforms to translation transforms breaks the translations.

We should do something along those lines:
```diff
@@ -44,7 +44,9 @@ def _flattenComponent(glyphSet, component):
     for nested in glyph.components:
         flattened_components = _flattenComponent(glyphSet, nested)
         for i, (_, tr) in enumerate(flattened_components):
-            tr = tr.transform(component.transformation)
-            flattened_components[i] = (flattened_components[i][0], tr)
+            flat_tr = Transform()
+            flat_tr = flat_tr.translate(*component.transformation[4:]).translate(*tr[4:])
+            flat_tr = flat_tr.transform(Transform(*component.transformation[:4])).transform(Transform(*tr[:4]))
+            flattened_components[i] = (flattened_components[i][0], flat_tr)
         all_flattened_components.extend(flattened_components)
     return all_flattened_components
```

**Comment by khaledhosny** [comment]
This seems to work for me:
```diff
diff --git a/Lib/ufo2ft/filters/flattenComponents.py b/Lib/ufo2ft/filters/flattenComponents.py
index aa234b6..72ebdc0 100644
--- a/Lib/ufo2ft/filters/flattenComponents.py
+++ b/Lib/ufo2ft/filters/flattenComponents.py
@@ -43,8 +43,10 @@ def _flattenComponent(glyphSet, component):
     all_flattened_components = []
     for nested in glyph.components:
         flattened_components = _flattenComponent(glyphSet, nested)
-        for i, (_, tr) in enumerate(flattened_components):
-            tr = tr.transform(component.transformation)
-            flattened_components[i] = (flattened_components[i][0], tr)
+        for i, (name, tr) in enumerate(flattened_components):
+            flat_tr = Transform(*component.transformation)
+            flat_tr = flat_tr.translate(tr.dx, tr.dy)
+            flat_tr = flat_tr.transform((tr.xx, tr.xy, tr.yx, tr.yy, 0, 0))
+            flattened_components[i] = (name, flat_tr)
         all_flattened_components.extend(flattened_components)
     return all_flattened_components
```

**Comment by arrowtype** [comment]
Not sure it’s useful to say, but I’ve run into problems here, as well.

![image](https://user-images.githubusercontent.com/45946693/102422943-dccdf080-3fd5-11eb-9f80-85d1315b89bb.png)

I can’t easily offer a simple reproduction case, but this the result of using `decomposeTransformedComponents` and `flattenComponents` at https://github.com/arrowtype/recursive/tree/b61385b2e6d40e4684fcc042957ec468863a4e94.

Related issue: https://github.com/googlefonts/fontbakery/issues/2961 (a FontBakery check for flattened components)
