### ISSUE TITLE
Default to cffsubr, deprecate then drop compreffor

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/ufo2ft#464]
Currently when building CFF 1 fonts `compreffor` is the default subroutinizer, but as we all know it is slow, really really show, and often produce larger tables than `cffsubr`.

I propose always defaulting to `cffsubr`, deprecate and eventually drop support for `compreffor` as I don’t see it serving much purpose anymore, but if you want to keep it for whatever reason, make it an optional dependency and and don’t install it by default.

**Comment by anthrotype** [comment]
I wonder, is it the extra dependency or the fact you have to pass an extra compile option that bothers you? To me it kind of bothers me a little bit more that changing default would suddenly modify the built output of existing font projects as they update ufo2ft.

**Comment by khaledhosny** [comment]
Both, but having to remember to override the default option for each project I work on is the more pressing issue.

The change to output happens all the time, for example a few releases ago feaLib started compiling to different lookup types and subtables to efficiently store the data, that is a more potentially problematic change than the low level subroutines that should cause no functional difference whatsoever.

**Comment by anthrotype** [comment]
ok, let's change default and keep it around for a while until it become a burden to maintain/update. PR?
