### ISSUE TITLE
TrueType outline compiler may change point indices

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/ufo2ft#469]
The TrueType outline compiler changes the point indices in some cases.

https://github.com/googlefonts/ufo2ft/blob/master/Lib/ufo2ft/outlineCompiler.py#L1301-L1316

This is because it uses a segment-based pen, which rotates the points so each contour starts with an oncurve point.

This is a problem for instructed glyphs, as it makes the instructions invalid. Using a point-based pen could solve the problem, but it doesn't exist in fontTools.

**Comment by anthrotype** [comment]
Let's make a TTGlyphPointPen. Want to work on a PR?

**Comment by jenskutilek** [comment]
I'll have a shot at it.

**Comment by anthrotype** [comment]
@jenskutilek would you like to work on a PR to ufo2ft for using the new TTGlyphPointPen?

**Comment by anthrotype** [comment]
ah I forgot, you already made one 😅  
https://github.com/googlefonts/ufo2ft/pull/478
