### ISSUE TITLE
[MarkFeatureWriter] Rename anchors with invalid characters

### ISSUE THREAD

**Issue by moyogo** [googlefonts/ufo2ft#477]
For example in https://github.com/googlefonts/glyphsLib/issues/963 there's an anchor called `#topRight`.

**Comment by JelleBosmaMT** [comment]
A #topright anchor should be ignored for feature code, not renamed.

**Comment by anthrotype** [comment]
is that `#` some unwritten convention which we were not aware of?

**Comment by anthrotype** [comment]
I just saw @JelleBosmaMT other comment https://github.com/googlefonts/fontmake/issues/745#issuecomment-789826696

so that means we should handle this as a new Glyphs-specific feature. Possibly propose this to ufo-spec if useful more generally

**Comment by anthrotype** [comment]
... or maybe just go on and modify ufo2ft MarkFeatureWriter to take advantate of this, since we're already baking in a lot of Glyphs-app specific assumption that technically are not standard in UFO-world

**Comment by khaledhosny** [comment]
Regardless of this particular anchor name, I think this is a general issue and need to be handled here since feature files put restrictions on anchor names that UFO does not have.

From https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#anchor:
> An arbitrary name for the anchor. This attribute is optional. Name must not contain control characters.

So, for example, spaces are OK but the generated feature code will be broken (I did actually encounter a font with spaces in anchor names, though it was converted originally from a non-UFO format).

**Comment by anthrotype** [comment]
Khaled is right, this needs to be addressed regardless of support for skipping `#`-prefixed anchors, since FEA syntax has some stricter requirements than UFO about naming things like anchors.

**Comment by madig** [comment]
https://glyphsapp.com/learn/reusing-shapes-component-tricks#g-__repurposing-cursive-attachment-for-ligatures says you can use anything non-lettery for anchors that should be used only for construction. I suppose this could be another opt-in filter inserted by glyphsLib, to remove anchors starting with non-letters.

**Comment by schriftgestalt** [comment]
Underscores means that this anchor should attach to some other anchor. And mostly that means it is a mark. But can be a pice of a letter, too. You don’t need to filter custom anchor names. Just look if the glyph that constants the underscore version is a proper mark glyph. In glyphs, I build the mark classes first and then only use those anchors that has a mark class.

**Comment by khaledhosny** [comment]
This is fixed by #869 as it now ignores anchors such as `#top`. Closing this now until someone comes up with another anchor naming scheme that could result in invalid feature code.
