### ISSUE TITLE
Avoid "reloading" TTFonts in PostProcessor.__init__

### ISSUE THREAD

**Issue by madig** [googlefonts/ufo2ft#485]
Going from https://github.com/fonttools/fonttools/issues/1095, quite some time is spent serializing/deserializing fonts somewhere inbetween compiling the final binary. This slows down the entire process. `PostProcessor.__init__` seems to "reload" every font, maybe to clean up loose data? I think it should maybe just work with what it's given?

**Comment by simoncozens** [comment]
One thing the postprocessor does is rename the glyphs to production names. It's very hard to do this without a save/load, because internal to fonttools, glyphs are referred to by name, not by GID. If you change `alef-ar` to `uni0627` in GlyphOrder, but font["GSUB"].table.LookupList.Lookups[5].Subtable[0].InputCoverage[0] still refers to `alef-ar`, your font will no longer save. So it's easier to save and reload than to go through every subtable everywhere trying to remap things.

**Comment by madig** [comment]
_Argh_. That's what I'm running into locally... So, what do?

**Comment by anthrotype** [comment]
yes, what Simon said.
however not that for VFs I think we do the glyph renaming only on the final VF, not on each master TTF

**Comment by anthrotype** [comment]
maybe the postprocessor should only do the reloading if it's going to actually rename glyphs, not unconditionally like now

**Comment by madig** [comment]
There's a few other things that happen, I'll push a branch.

**Comment by behdad** [comment]
Renaming glyphs is such a misunderstood op. One can build a font, make sure all tables are compiled, then do the renaming glyphs, which would involve just loading and saving the post table...

**Comment by behdad** [comment]
Or should even be possible to provide the rename mapping at load time.

**Comment by behdad** [comment]
So, a lot of this would be a non-issue if we were dealing with immutable data types, such that any modification would involve copy-on-write duplication... Many functional languages work that way. In Python, I'm sure there's some dark black magic with metaclasses to get some of that, but there will be dragons. Also, there's no way to get compile-time errors for violations with Python.

Anyway, attrs2 on this: https://www.attrs.org/en/stable/examples.html#immutability

**Comment by madig** [comment]
I'd take some immutability, but the issues I'm seeing is data normalization (e.g. post.italicAngle of 0.0 does not get normalized to 0 like when reloading), data sorting (e.g. name table being in a different order) and glyph names staying as they are :neutral_face:

**Comment by behdad** [comment]
I see.

**Comment by madig** [comment]
So, what do? Ideally the compilation pass spits out something that we don't need to reload to make it mergable. Or we reload as little as possible? Any insights appreciated over at https://github.com/googlefonts/ufo2ft/pull/486.

**Comment by behdad** [comment]
> So, what do? Ideally the compilation pass spits out something that we don't need to reload to make it mergable.

Yes, I'm happy to work on making that reality.

> Or we reload as little as possible? Any insights appreciated over at #486.

Okay great. That gives me a point to start. Let's continue there.

**Comment by madig** [comment]
So, going from https://github.com/googlefonts/ufo2ft/pull/486, I stumbled over the following when reloading strictly only for renaming or post version changes:

- maxp table missing values
- various post attributes being filled with verbatim Python types rather than the final value
- the post extraNames list not being filled in
- the STAT table not having AxisValueCount filled in
- the name table being unsorted

**Comment by behdad** [comment]
> * the post extraNames list not being filled in

We should completely remove `extraNames`. It serves no functional purpose.

**Comment by behdad** [comment]
> * the STAT table not having AxisValueCount filled in

Just make the STAT builder set it. The Count values in all of otData are also redundant and could be removed if we are willing to take the breakage and update code depending on it.

**Comment by khaledhosny** [comment]
> The Count values in all of otData are also redundant and could be removed

Yes, please! It always seemed odd to have a separate Count field when the data is stored in a Python list anyway.

**Comment by behdad** [comment]
I feel like a fonttools API break is gaining support...

**Comment by madig** [comment]
Would this conflict with fT's ability to carry and serialize meaningless/wrong input data in loaded fonts or is it sufficiently high level that that makes little sense? Is that even a design goal?

**Comment by khaledhosny** [comment]
These `*Count`s are written as comments in TTX, so probably can be kept regardless of the API change. In Python, `LookupCount` would be replaced by `len(Lookup)` and so on. May be the first step would to stop using these `*Count`s internally but set them when decompiling, so code building tables from scratch don’t have to set them, and later be removed entirely.

**Comment by behdad** [comment]
> Would this conflict with fT's ability to carry and serialize meaningless/wrong input data in loaded fonts or is it sufficiently high level that that makes little sense?

The count values are always ignored when compiling the font.

> Is that even a design goal?

Nope. We don't even pretend.

> These `*Count`s are written as comments in TTX, so probably can be kept regardless of the API change. In Python, `LookupCount` would be replaced by `len(Lookup)` and so on. May be the first step would to stop using these `*Count`s internally but set them when decompiling, so code building tables from scratch don’t have to set them, and later be removed entirely.

Or replace them with properties that warn when accessed; set a deadline for removing them, and advise code to switch. The replacement code can even be offered in the warning.
