### ISSUE TITLE
[MarkFeatureWriter] _logIfAmbiguous too noisy

### ISSUE THREAD

**Issue by behdad** [googlefonts/ufo2ft#488]
Building NotoSans-MM, I get hundreds of log messages like:
```
INFO:ufo2ft.featureWriters.markFeatureWriter.MarkFeatureWriter:The base glyph uniA7BD and mark glyph uniA64D are ambiguously connected by several anchor classes: MC_top, MC_bottom. The last one will prevail.
INFO:ufo2ft.featureWriters.markFeatureWriter.MarkFeatureWriter:The base glyph uniA7BE and mark glyph uniA64C are ambiguously connected by several anchor classes: MC_top, MC_bottom. The last one will prevail.
```
I don't know why these still exist in NotoSans-MM. But if they are fine being there, then the verbose messages should at least be removed and by default maybe write just one message.

**Comment by behdad** [comment]
I suggest by default not calling that function at all. Change the INFO to DEBUG maybe.

**Comment by madig** [comment]
Mh, I'd personally would like to keep those. If you're inspecting fontmake output, I find that the default should be to set the severity level to WARNING.

**Comment by behdad** [comment]
> If you're inspecting fontmake output, I find that the default should be to set the severity level to WARNING.

Right. That works for me as well.

**Comment by khaledhosny** [comment]
Continuing in #563
