### ISSUE TITLE
FILTERS_KEY rename to UFO2FT_FILTERS_KEY is a breaking change

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/ufo2ft#489]
The recent name of FILTERS_KEY to UFO2FT_FILTERS_KEY is a breaking change. Or am I not supposed to use that key from client code?

**Comment by justvanrossum** [comment]
Ah, I see I should have used the one from `ufo2ft.constants` all along.

**Comment by moyogo** [comment]
Sorry, I guess we should have done a smoother renaming.

**Comment by justvanrossum** [comment]
It's hard to emit deprecation warnings for constants...
