### ISSUE TITLE
Should ufo2ft.filters.transformations change the advance width?

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/ufo2ft#490]
I feel like it should change the advance widths when the glyphs are scaled, but currently it doesn't. Happy to write a PR if we think it should.

**Comment by anthrotype** [comment]
the filter was originally added to mimic the behavior of Glyphs.app Transformations filter. What does it do about advances?

**Comment by simoncozens** [comment]
It scales them.

**Comment by anthrotype** [comment]
does it automatically whenever there's a scale, or are they treated separately?

**Comment by simoncozens** [comment]
No, automatically when there's a scale set.

**Comment by moyogo** [comment]
A PR would be nice :-).

This reminds me, https://github.com/googlefonts/ufo2ft/pull/238 needs to be rebased so ufo2ft's filter can also handle metrics independently.
