### ISSUE TITLE
postscriptSlantAngle is overriden by italicAngle

### ISSUE THREAD

**Issue by madig** [googlefonts/ufo2ft#508]
```
In [3]: u = Font()

In [6]: u.info.italicAngle = 10

In [7]: u.info.postscriptSlantAngle = 20

In [8]: t = ufo2ft.compileTTF(u)

In [11]: assert t["post"].italicAngle == 20, t["post"].italicAngle
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-11-e1fd7231bc4c> in <module>
----> 1 assert t["post"].italicAngle == 20, t["post"].italicAngle

AssertionError: 10.0
```

**Comment by anthrotype** [comment]
what's the purpose of postscriptSlantAngle given there's italicAngle already? And why/when would they ever be distinct? (first time I realize that UFO has two fields denoting the same thing)

**Comment by anthrotype** [comment]
looks like postscriptSlantAngle is completely ignored in favour of italicAngle, e.g.

https://github.com/googlefonts/ufo2ft/blob/52408187e78296372c6983119fb9e310c0080b38/Lib/ufo2ft/outlineCompiler.py#L923-L924

and when missing postscriptSlantAngle falls back to italicAngle anyway. What do you suggest to do? Use postscriptSlantAngle (with fallback to italicAngle) every where italicAngle is currently used?

**Comment by moyogo** [comment]
The destinction between italic angle and slant angle is present in [FontLab 5](http://www.e-font.de/flpydoc/):
>  slant_angle
>  italic_angle(float) - Italic Angle

The Type1 and CFF specs only mention ItalicAngle.

**Comment by anthrotype** [comment]
i'm not sure i understand the difference between the two, could you pls elaborate?

**Comment by madig** [comment]
My idea would be to use postscriptSlantAngle if available and fall back to italicAngle, simply to do what I'd expect should happen. Low priority though.

**Comment by moyogo** [comment]
The [FontLab 5 for Windows manual](https://help.fontlab.com/pdf/FLS5WinManual.pdf?page=245) says the following:
> Italic Angle
> Actual italic or oblique angle for the font. The italic angle is measured in the counterclockwise direction, so the default value is -12º
> 
> Slant Angle
> Type 1 fonts can be artificially slanted to get an “oblique” appearance while keeping the actual outlines upright. Enter a slant angle value (in degrees) here and check the result in the Preview panel 

I don't think the postscriptSlantAngle should be used for the post table italicAngle.

**Comment by moyogo** [comment]
postscriptSlantAngle would probably affect SyntheticBase or FontMatrix in CFF/Type1 fonts.

**Comment by anthrotype** [comment]
Still unclear to me what to do with UFO's `postscriptSlantAngle`, maybe our friends at Adobe can shed some light /cc @punchcutter @cjchapman @josh-hadley

**Comment by josh-hadley** [comment]
@anthrotype I did some digging around here. [AFDKO](https://github.com/adobe-type-tools/afdko) has one tool that specifically references `postscriptSlantAngle`, and it is in a kind of "pass-through" (with rounding) UFO-to-UFO scheme. As best I can tell, it's not used to fill in any value in sfnt-housed or Type1 fonts.

I don't know the genesis of this item in the UFO spec but folks here suggested that @typesupply, @benkiel, or @LettError might know more. From the descriptions of other `postscript*` key definitions in the [UFO Spec](https://unifiedfontobject.org/versions/ufo3/fontinfo.plist/), it doesn't seem like it was intended to be used for the 'post' table's italicAngle value or any other sfnt table value. Other `postscript*` key definitions explicitly state the font value they correspond to, but not `postscriptSlantAngle`. Maybe it was intended to be used by UFO-based tools for synthesizing italics 🤷 ?

**Comment by typesupply** [comment]
> I don't know the genesis of this item in the UFO spec but folks here suggested that @typesupply, @benkiel, or @LettError might know more.

This was a FontLab value that dates back to UFO 1. It, like a lot of the UFO 1 font info fields, was included simply because it was something we could access in VFB and we were trying to round trip as much data as we possibly could. Maybe the FontLab documentation from that time details what it was used for.

**Comment by benkiel** [comment]
From the notes to the Postscript info in the UFO spec:

> The Type 1/CFF/post table italicAngle field can be found at the generic italicAngle attribute

I did a quick search of the CFF/T1 spec and didn't see slant angle. If I had to guess, that likely came from the aforementioned FL5 font data. @josh-hadley am I missing that value in an Adobe spec?

Either way, the UFO spec says that `postscriptSlantAngle` is the artificial slant angle, so I wouldn't use it for the italic angle.

The postscriptSlantAngle is still referenced in the FL7 python documenation, but it doesn't say what postscript value it is associated with. I'm guessing now that there isn't one (?). Also nothing helpful in the unofficial FL 4/5 python doc.

**Comment by typesupply** [comment]
From the Mac FontLab 5 manual (User manual release 5.1 [5/2006]), page 243:

> Slant angle
> Type 1 fonts can be artificially slanted to get an “oblique” appearance while keeping the actual outlines upright. Enter a slant angle value (in degrees) here and check the result in the Preview panel

**Comment by josh-hadley** [comment]
> I did a quick search of the CFF/T1 spec and didn't see slant angle. If I had to guess, that likely came from the aforementioned FL5 font data. @josh-hadley am I missing that value in an Adobe spec?

You're not missing anything. It's _italicAngle_. There's no "slant" angle in the T1/CFF specs. Maybe what @moyogo is saying about `FontMatrix` is the right idea -- the `postscriptSlantAngle` could have been a way for a tool (FontLab, specifically) to set `FontMatrix` to artificially slant outlines.

> Either way, the UFO spec says that `postscriptSlantAngle` is the artificial slant angle, so I wouldn't use it for the italic angle.

I agree.

**Comment by madig** [comment]
Fanatstic info here, thanks! This issue can go away now as I was misinformed :)

**Comment by anthrotype** [comment]
thank you all for the clarifications

**Comment by moyogo** [comment]
Here's a screenshot of the relevant section of the FLS5 Font Info > Metrics and Dimensions > Key Dimensions panel with the description "Slant is based on FontMatrix and works only in T1".
<img width="355" alt="Screenshot 2021-06-24 at 19 41 24" src="https://user-images.githubusercontent.com/1923747/123316514-d2f8ed00-d524-11eb-9f3d-bfa6680f09f3.png">

Here's a screenshot of Fontforge with two test fonts produced in FLS5, one with the default Slant angle value and another with a custom Slant angle value set to -12. Note that in FLS5 the source or the generated Win Type 1 fonts are exactly the same except for the Slant angle value whereas in Fontforge the one with the Slant angle set to -12 has slanted glyphs.
<img width="151" alt="Screenshot 2021-06-24 at 19 45 59" src="https://user-images.githubusercontent.com/1923747/123316991-6af6d680-d525-11eb-893e-83818e086aa3.png">

**Comment by twardoch** [comment]
When you set Slant Angle on FLS5, the contours were upright in the Glyph Window but were rendered slanted in Metrics and Font Window, and on the previews. 

Slant Angle was exported as FontMatrix slant into T1/CFF, and a slant was physically applied on TTF export.

Slant Angle was very rarely used, and we didn't implement it in FLVI/FL7.

**Comment by twardoch** [comment]
Edit: FLS5 only used FontMatrix with T1. For CFF, it slanted physically, because there were problems in early implementations of OpenType with a non-1 0 0 1 0 0 FontMatrix. 

Remember how InDesign once didn't like non-1000 UPM OTFs? Early Mac OS X also didn't deal with them well. 

Similar problems occurred when FontMatrix was used in OTF/CFF for slant, so FLS5 applied the slant too the outlines.
