### ISSUE TITLE
Feature File Warning not edit in Glyphs

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/ufo2ft#525]
```
# Do not use Glyphs to edit features.
#
# This Glyphs file was made from several UFOs that had different
# features. As a result, the features are not editable in Glyphs and
# the original features will be restored when you go back to UFOs.
```

I would like to not care about the original features and edit them anyway in Glyphs. I thought I removed the link between the source file and the .fea file, but apparently not. Is there a way to to remove the original features definitely, and to not have them restored in any way?

**Comment by belluzj** [comment]
From Glyphs.app, remove this field from your masters' `userData`: `com.schriftgestaltung.Glyphs.originalFeatureCode`

That should prevent glyphsLib from restoring old imported features.fea code.

https://github.com/googlefonts/glyphsLib/blob/9271c32e5135dbaebfb852c3d40246967fbe232d/Lib/glyphsLib/builder/features.py#L35-L38

**Comment by RosaWagner** [comment]
Thanks @belluzj for the quick reply.
I searched for this kind of key and couldn't find it visible in font/master/instance info (neither Glyphs 2 nor 3). There was not so much masters, so I converted to UFO, removed the inconsistant features and reconverted to Glyphs. It worked, but a tuto for next user having this problem would be awesome.

**Comment by khaledhosny** [comment]
Does not seem like a ufo2ft issue.
