### ISSUE TITLE
Misleading project description

### ISSUE THREAD

**Issue by Apteryks** [googlefonts/ufo2ft#605]
Hello,

Reading the project description, I was a bit puzzled to learn that "ufo2ft ("UFO to FontTools") is a fork of ufo2fdk **whose goal is to generate OpenType font binaries from UFOs without the FDK dependency.**".  The problem is that it depends of the `cffsubr` Python package, which builds its own copy of ADFKO (it relies on its `tx` command).

Does it mean this project failed to meet its goal? :-)

**Comment by khaledhosny** [comment]
cffsubr raison d'etre is to have the AFDKO subroutinizer without needing ful AFDKO install.

**Comment by Apteryks** [comment]
Alright, thanks for confirming.

**Comment by Apteryks** [comment]
I was asking because after packaging it on Guix, where dependencies are shared rather than bundled, it was made obvious that the dependency to ADFKO was retained through `tx`).  So the only gain is saving a few MiB of non-tx binaries (the full ADFKO install uses about 9 MiB here).
