### ISSUE TITLE
Use `fontTools.cu2qu` on non-CPython?

### ISSUE THREAD

**Issue by madig** [googlefonts/ufo2ft#632]
AFAIU, the separate cu2qu dependency is for building binary wheels, but Pypy is probably better off using the pure-Python code imported into fontTools directly. It will fetch the pure Python wheel regardless, but it's basically an extra depedency that isn't necessary?

**Comment by anthrotype** [comment]
the next fonttools release will include binary wheels for all cpythons/platforms except pypy (where pure python works best). once that is out we can finally change the imports and drop the dependency on the standalone cu2qu (which we were using only because of the binary wheels basically).
