### ISSUE TITLE
Kerning not active for non-default languages

### ISSUE THREAD

**Issue by yanone** [googlefonts/ufo2ft#699]
I'm guessing in the wake of the recent work on splitting kerning by scripts, kerning support got lost for non-default languages. (I'm using the lastest `main` codebase)

Notice how `ldot` get replaced for Catalan but the kerning pair `Pa` disappears in the lower screenshot.

<img width="1469" alt="Bildschirm­foto 2023-02-05 um 15 17 00" src="https://user-images.githubusercontent.com/175386/216824844-49f2b677-96fd-4638-8c23-07cd1c56e4d2.png">
<img width="1469" alt="Bildschirm­foto 2023-02-05 um 15 17 08" src="https://user-images.githubusercontent.com/175386/216824849-df77f003-5e51-4c39-83d4-47051ca9e675.png">

Peeking into the feature file as produced by `fontmake` confirms:

```
feature kern {
    script DFLT;
    language dflt;
    lookup kern_Default;
    
    script arab;
    language dflt;
    lookup kern_Default;
    lookup kern_Arab;
    
    script cyrl;
    language dflt;
    lookup kern_Default;
    lookup kern_Cyrl;
    
    script grek;
    language dflt;
    lookup kern_Default;
    lookup kern_Grek;
    
    script latn;
    language dflt;
    lookup kern_Default;
    lookup kern_Latn;
} kern;
```

**Comment by yanone** [comment]
cc @madig

**Comment by anthrotype** [comment]
did you define latn CAT in the global languagesystems?

**Comment by anthrotype** [comment]
or is there another GPOS feature apart from kern that uses `script latn; language CAT`?

**Comment by yanone** [comment]
Yes, these language systems are defined:

```
languagesystem DFLT dflt; # Default, Default
languagesystem grek dflt; # Greek, Default
languagesystem arab dflt; # Arabic, Default
languagesystem latn dflt; # Latin, Default
languagesystem cyrl dflt; # Cyrillic, Default
languagesystem latn CAT; # Latin, Catalan
languagesystem latn NLD; # Latin, Dutch
languagesystem latn KAZ; # Latin, Kazakh
languagesystem latn TAT; # Latin, Tatar
languagesystem latn TRK; # Latin, Turkish
languagesystem latn CRT; # Latin, Crimean Tatar
languagesystem latn AZE; # Latin, Azeri
languagesystem latn MOL; # Latin, Moldavian
languagesystem latn ROM; # Latin, Romanian
languagesystem latn VIT; # Latin, Vietnamese
languagesystem cyrl BGR; # Cyrillic, Bulgarian
languagesystem cyrl SRB; # Cyrillic, Serbian
languagesystem arab URD; # Arabic, Urdu
```

All non-default languages are missing kerning.

I didn't check then, but I checked now: No other kerning features are defined other than the one already posted at the top.

**Comment by yanone** [comment]
> or is there another GPOS feature apart from kern that uses script latn; language CAT?

Sorry, I didn't answer your question correctly. I don't have any other `GPOS` features for these languages. They are all used in the `locl` feature, so they're `GSUB`.

**Comment by anthrotype** [comment]
seems to be intentional:

https://github.com/googlefonts/ufo2ft/blob/5a5f6dfdebeaaaa50de0b927f122776f3783e1d9/Lib/ufo2ft/featureWriters/kernFeatureWriter.py#L507-L511

but it is nevertheless a bug in my opinion. The old kernFeatureWriter would register to all declared languages, not just dflt.
Can you use ufo2ft v2.30.0 (stable release) instead of the pre-release or github main branch? at least while we investigate/fix
thanks for reporting

**Comment by yanone** [comment]
> Can you use ufo2ft v2.30.0 (stable release)

No, because the kerning of v2.30.0 was faulty for my font to begin with, which triggered Nikolaus rewriting it. It's not super urgent for me. As long as it gets recognized as an important bug that must affect all fonts, I'll wait. Thank you

**Comment by madig** [comment]
Todo: add all languages the designer defined for existing scripts, keep using "dflt" for scripts we add dynamically.

**Comment by madig** [comment]
@yanone can you please test with https://github.com/googlefonts/ufo2ft/pull/711?

**Comment by yanone** [comment]
@madig Looks good!
