### ISSUE TITLE
Allow any casing of "# Automatic Code"?

### ISSUE THREAD

**Issue by madig** [googlefonts/ufo2ft#701]
One of ours just stumbled over this, you need to spell the feature insertion marker exactly as `# Automatic Code`, otherwise stuff silently doesn't work. Does Glyphs.app allow any case? If so, we should, too.

**Comment by madig** [comment]
@schriftgestalt hi! Does Glyphs.app care about the casing of the marker?

**Comment by madig** [comment]
So, using a different casing in some Noto font I found and clicking "compile" pops up some error, which disappears if I return to capital casing. I then suppose the answer is "no".

**Comment by madig** [comment]
But maybe ufo2ft should at least warn when encountering unexpected casing.

**Comment by schriftgestalt** [comment]
It needs to be written exactly like this.
