### ISSUE TITLE
hhea.caretSlopeRun calculated using math.tan() instead of math.atan()

### ISSUE THREAD

**Issue by yanone** [googlefonts/ufo2ft#703]
The two lines at the top and bottom [here](https://github.com/googlefonts/ufo2ft/blob/a5267d135d5a8dba7e6a5d3ac44139afa6159429/Lib/ufo2ft/fontInfoData.py#L147-L162) are wrong. `math.atan()` is used to calculate the triangle legs from a given angle, `math.tan()` is used for the inverse, to calculate the angle from the leg length.

This is correct:

```python
import math
italicAngle = -12
caretSlopeRun = math.atan(math.radians(-italicAngle)) * 1000
roundTrippedItalicAngle = math.degrees(math.tan(-caretSlopeRun / 1000))
print(italicAngle, caretSlopeRun, roundTrippedItalicAngle)
```

prints:

```
-12 206.45531758085963 -12.000000000000002
```

I can make a PR.

**Comment by yanone** [comment]
The current code calculates 213 as the careSlopeRun for -12°, which is probably close enough that no one ever noticed the mistake.

**Comment by anthrotype** [comment]
good catch, please send PR thanks

**Comment by yanone** [comment]
My proposal is wrong. ufo2ft had it right all along.
