### ISSUE TITLE
DottedCircleFilter module misnamed?

### ISSUE THREAD

**Issue by madig** [googlefonts/ufo2ft#707]
Doing https://github.com/googlefonts/ufo2ft/blob/5a5f6dfdebeaaaa50de0b927f122776f3783e1d9/Lib/ufo2ft/filters/dottedCircleFilter.py#L24-L32 results in this error:

```txt
ERROR:ufo2ft.filters:Failed to load filter: {'name': 'DottedCircleFilter', 'pre': True}
Traceback (most recent call last):
  File "/home/nikolaus/googlesans-flex/venv/lib/python3.11/site-packages/ufo2ft/filters/__init__.py", line 64, in loadFilters
    filterClass = getFilterClass(filterDict["name"], namespace)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolaus/googlesans-flex/venv/lib/python3.11/site-packages/ufo2ft/filters/__init__.py", line 52, in getFilterClass
    return getattr(module, className)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ufo2ft.filters.dottedCircleFilter' has no attribute 'DottedCircleFilterFilter'
```

I suppose the module is misnamed and should lose the `Filter` part?

**Comment by anthrotype** [comment]
you mean the _class_ name is misnamed

https://github.com/googlefonts/ufo2ft/blob/5a5f6dfdebeaaaa50de0b927f122776f3783e1d9/Lib/ufo2ft/filters/__init__.py#L46-L51

the name in the lib's filter should be "DottedCircle" (or even "Dotted Circle" or "dottedCircle" would work).
We can fix that function to not append "Filter" suffix if it's already there if you like

**Comment by madig** [comment]
Hm yes, at least avoiding stuff like FooFilterFilter would make sense.
