### ISSUE TITLE
Compiling UFO failed | Add Geom #4874

### ISSUE THREAD

**Issue by ThanosPoulakidas** [googlefonts/ufo2ft#735]
Hi,

I am facing a problem in the Build font phase with the title "Compiling UFO failed: ('Trying to perform operation on unsupported segment type.', 'qcurve')".
Below is the link:
[https://github.com/ThanosPoulakidas/Geom/actions/runs/4642217081/jobs/8215890912#step:10:218](https://github.com/ThanosPoulakidas/Geom/actions/runs/4642217081/jobs/8215890912#step:10:218)

It may be similar to this [issue](https://github.com/googlefonts/ufo2ft/issues/468) but I am not very familiar with this.

**Comment by ThanosPoulakidas** [comment]
@simoncozens in case you want to close this issue too

**Comment by simoncozens** [comment]
We're discussing this in https://github.com/google/fonts/issues/4874
