### ISSUE TITLE
ufo2ft adds `openTypeNamePreferredSubfamilyName` without adding `openTypeNamePreferredFamilyName`

### ISSUE THREAD

**Issue by typoman** [googlefonts/ufo2ft#744]
This might not be a bug, but in case these two fields are not filled in a ufo, ufo2ft only adds the `openTypeNamePreferredSubfamilyName` and not the second. I couldn't also force ufo2ft not to add `openTypeNamePreferredSubfamilyName` if it's set to None. If a font is already defined as a RBIBI font in the `styleMapStyleName` this is not required.

https://github.com/googlefonts/ufo2ft/blob/0d2688cd847d003b41104534d16973f72ef26c40/Lib/ufo2ft/outlineCompiler.py#L418

- Shouldn't both IDs 16 and 17 be included and not only just one? 
- How can I force ufo2ft not to delete the ID 16 if I had already added it myself manually?

**Comment by behdad** [comment]
> If I'm understanding this correctly, you're proposing that ufo2ft only omits nameID 16 and 17 if _both_ are equal to their respective legacy nameID 1 and 2, otherwise keep them both: e.g. from

That makes sense to me.

**Comment by anthrotype** [comment]
> I can share an example later if needed

that would be nice, thanks
