### ISSUE TITLE
Cham goes to the USE shaper, not Indic

### ISSUE THREAD

**Issue by behdad** [googlefonts/ufo2ft#751]
This line looks wrong to me:
https://github.com/googlefonts/ufo2ft/blob/0d2688cd847d003b41104534d16973f72ef26c40/Lib/ufo2ft/constants.py#L53

What's the history?

**Comment by khaledhosny** [comment]
It was introduced in https://github.com/googlefonts/ufo2ft/commit/5b4476db89edad762a928103a7a885bb94050da0 (from #257).

**Comment by simoncozens** [comment]
Which in turn points to https://github.com/googlefonts/ufo2ft/issues/179#issuecomment-390391382.

**Comment by behdad** [comment]
Yeah I think we should move it to the USE list below the Indic list then.  That list also needs updating to Unicode 15 as well.

**Comment by behdad** [comment]
There's also a typo in the USE list:
```
    "tfng",  # Tifinagh
```
Should be uppercase.

@anthrotype should those two lists be sets instead?
