### ISSUE TITLE
Support public.fontInfo lib key for variable fonts

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/ufo2ft#812]
As defined in https://github.com/fonttools/fonttools/pull/3358

**Comment by anthrotype** [comment]
I believe it should be sufficient that we merge the public.fontInfo dictionary with the base master UFO's fontinfo (copying the latter if inplace=False) and then proceed to build the VF as usual

**Comment by khaledhosny** [comment]
I’m working on this but modifying source UFOs does not work with multiple variable-fonts as the source fonts seem to be built only once.

**Comment by khaledhosny** [comment]
I’m feeling this is better handled by the postProcessor after merging the source fonts. It will probably result in some duplicated code, but it seems cleaner and less error-prone.
