### ISSUE TITLE
Instantiator should not complain about missing glyphs in non-default layers

### ISSUE THREAD

**Issue by madig** [googlefonts/ufo2ft#836]
For some reason, I wrote https://github.com/googlefonts/ufo2ft/blob/8e9e6eb66a2d22714c9da9544bdbfe1aa44d0cf0/Lib/ufo2ft/instantiator.py#L292-L295 a long time ago and now I see for the first time a warning about a sparse master not containing all the other glyphs. Well, duh. I wonder why I didn't catch this earlier...

**Comment by anthrotype** [comment]
the warning is about glyphs that are in the non-default layer but not in the default one. it is a valid warning because glyphs that are not in the default master basically do not exist.
what is the problem again?

**Comment by anthrotype** [comment]
the instantiator is not complaining "about missing glyphs in non-default layers" but rather "about extra glyphs that are not in the default layer"

**Comment by madig** [comment]
Ignore me, I managed to reference the wrong UFO file and jumble everything.
