### ISSUE TITLE
Ligature carets present in the GDEF table but not being taken into account

### ISSUE THREAD

**Issue by adbac** [googlefonts/ufo2ft#894]
Hello,
I am using fontmake to build fonts outside of RoboFont: I have ligature carets that are defined with anchors named caret_1, caret_2 and so on. However after the fonts are built, the GDEF table contains the ligature carets (I checked and the numbers are good) but they have no effect, no matter in what context the font is used: webpage, text editing app or a graphic design software...

My ligature caret anchor in the ligature glyph:

![Image](https://github.com/user-attachments/assets/5b9f11bf-a7fc-4f2a-b050-15aec4ef2875)

The GDEF table with ligature carets definition:

![Image](https://github.com/user-attachments/assets/862a08ef-eee1-4d75-8ee6-ceba95ffe02a)

The ligature, with the caret position not being respected:

![Image](https://github.com/user-attachments/assets/938e513e-9a0d-44ef-8eb4-dfb11b0fa637)

I know this is kind of a cosmetic issue and some fonts don't even declare ligature carets 😅

**Comment by behdad** [comment]
> they have no effect, no matter in what context the font is used: webpage, text editing app or a graphic design software...

Very few pieces of software implement ligature carets I'm afraid. I think the Linux GNOME desktop (or GTK apps in general) do, and LibreOffice does.

cc @khaledhosny

**Comment by khaledhosny** [comment]
Apple’s CoreText (at least in TextEdit) also support ligature carets. I’m not aware of any other applications that use it. Most notably, no web browser or design software make use of it.

**Comment by khaledhosny** [comment]
A couple of years ago or so it was not used anywhere.
